spring:
  application:
    name: Spring-OAuth2ClientExample
  config:
    import: file:.env.properties
  security:
    oauth2:
      client:
        registration:
          authentik:
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            client-name: Authentik
            provider: authentik
        provider:
          authentik:
            authorization-uri: https://auth.wfis.lol/application/o/authorize/
            token-uri: https://auth.wfis.lol/application/o/token/
            user-info-uri: https://auth.wfis.lol/application/o/userinfo/
            user-name-attribute: sub
            jwk-set-uri: https://auth.wfis.lol/application/o/zti-sem-credentials/jwks/